development: 
  adapter: mysql2
  database: accq_dev
  encoding: utf8
  host: localhost
  username: <%=ENV['DB_USER']%>
  password: <%=ENV['DB_PASS']%>

test:
  adapter: mysql2
  database: accq_test
  encoding: utf8
  host: localhost
  username: <%=ENV['DB_USER']%>
  password: <%=ENV['DB_PASS']%>

production:
  adapter: mysql2
  host: <%=ENV["DB_HOST"]%>
  username: <%=ENV["DB_USER"]%>
  password: <%=ENV["DB_PASS"]%>
  database: <%=ENV["DB_NAME"]%>
  port: <%=ENV["DB_PORT"]%>
